#!/usr/bin/env node
/*
 * Build compressed project media from content-source/<project>/ into
 * public/media/projects/<slug>/ and generate src/media.js.
 *
 *   node scripts/build-media.js          # encode missing clips only
 *   node scripts/build-media.js --force  # re-encode everything
 *   node scripts/build-media.js --plan   # only (re)write src/media.js
 *
 * Folder → project id mapping lives in SLUGS below (must match data.js ids).
 */
const fs = require("fs");
const path = require("path");
const { execFileSync, spawnSync } = require("child_process");

const ROOT = path.resolve(__dirname, "..");
const SRC = path.join(ROOT, "content-source");
const OUT = path.join(ROOT, "public", "media", "projects");
const JS = path.join(ROOT, "src", "media.js");
const FORCE = process.argv.includes("--force");
const PLAN_ONLY = process.argv.includes("--plan");

const SLUGS = {
  "viralify.xyz": "viralify",
  vexo: "vexo",
  GRANVISUAL: "granvisual",
  ilgustodelgrano: "ilgustodelgrano",
  breaktheloop: "breaktheloop",
  lotusclothing: "lotus",
  youscaleit: "youscaleit",
};

function probe(file) {
  const r = spawnSync("ffprobe", ["-v", "error", "-select_streams", "v:0",
    "-show_entries", "stream=width,height:format=duration", "-of", "json", file], { encoding: "utf8" });
  if (r.status !== 0) return null;
  try {
    const j = JSON.parse(r.stdout);
    const s = j.streams && j.streams[0];
    if (!s || !s.width) return null;
    return { width: s.width, height: s.height, duration: parseFloat(j.format && j.format.duration) || 0 };
  } catch { return null; }
}
const md5 = (file) => execFileSync("md5", ["-q", file], { encoding: "utf8" }).trim();

function titleFrom(name) {
  let s = name.replace(/\.[a-z0-9]{2,4}$/i, "");
  if (/^[A-Za-z0-9_\-]{6,}$/.test(s)) return "";           // junk ids (snaptik_123, aljfkbasa…)
  s = s.replace(/#[^\s#]+/g, " ").replace(/\s+/g, " ").trim();
  const m = s.match(/^(.{12,}?[.!?…])(?=\s|[A-Z]|$)/);
  if (m) s = m[1];
  if (s.length > 72) s = s.slice(0, 69).trim() + "…";
  return s;
}
function ffmpeg(args) {
  const r = spawnSync("ffmpeg", args, { stdio: ["ignore", "ignore", "pipe"], encoding: "utf8" });
  if (r.status !== 0) throw new Error(r.stderr.slice(-600));
}

const dirs = fs.readdirSync(SRC, { withFileTypes: true })
  .filter(d => d.isDirectory() && !d.name.startsWith(".")).map(d => d.name).sort();
const manifest = {};
const jobs = [];

for (const dir of dirs) {
  const slug = SLUGS[dir] || dir.toLowerCase().replace(/[^a-z0-9]+/g, "-");
  if (!SLUGS[dir]) console.warn(`! no slug mapping for "${dir}", using "${slug}"`);
  const srcDir = path.join(SRC, dir);
  const outDir = path.join(OUT, slug);
  fs.mkdirSync(outDir, { recursive: true });
  const files = fs.readdirSync(srcDir).filter(f => !f.startsWith(".")).sort((a, b) => a.localeCompare(b));
  const seen = new Set();
  const clips = [];
  let logo = null;
  for (const f of files) {
    const full = path.join(srcDir, f);
    if (/^logo\.(jpe?g|png)$/i.test(f)) { logo = full; continue; }
    const info = probe(full);
    if (!info) { console.warn(`  skip (not a video): ${dir}/${f}`); continue; }
    const hash = md5(full);
    if (seen.has(hash)) { console.warn(`  skip duplicate: ${dir}/${f}`); continue; }
    seen.add(hash);
    clips.push({ src: full, name: f, ...info });
  }
  let cover = clips.findIndex(c => c.width >= 720 && c.duration >= 10 && c.duration <= 30);
  if (cover < 0) cover = 0;
  const entry = { logo: null, cover, clips: [] };
  clips.forEach((c, i) => {
    const n = String(i + 1).padStart(2, "0");
    entry.clips.push({ file: `${slug}/clip-${n}.mp4`, poster: `${slug}/clip-${n}.jpg`, title: titleFrom(c.name), duration: Math.round(c.duration) });
    jobs.push({ type: "video", src: c.src, mp4: path.join(outDir, `clip-${n}.mp4`), jpg: path.join(outDir, `clip-${n}.jpg`), label: `${slug}/clip-${n}` });
  });
  if (logo) { entry.logo = `${slug}/logo.jpg`; jobs.push({ type: "logo", src: logo, out: path.join(outDir, "logo.jpg"), label: `${slug}/logo` }); }
  manifest[slug] = entry;
}

// Write src/media.js first so the app builds while encoding is still running.
fs.writeFileSync(JS, `// AUTO-GENERATED by scripts/build-media.js — do not edit by hand.
// Re-run:  node scripts/build-media.js   (--force to re-encode everything)
const P = \`\${process.env.PUBLIC_URL || ""}/media/projects\`;
const m = (f) => \`\${P}/\${f}\`;

const raw = ${JSON.stringify(manifest, null, 2)};

export const media = Object.fromEntries(
  Object.entries(raw).map(([id, p]) => [id, {
    logo: p.logo ? m(p.logo) : null,
    cover: p.cover,
    clips: p.clips.map(c => ({ ...c, src: m(c.file), poster: m(c.poster) })),
  }])
);
`);
console.log(`wrote src/media.js — ${Object.keys(manifest).length} projects, ${jobs.filter(j => j.type === "video").length} clips`);
if (PLAN_ONLY) process.exit(0);

let n = 0;
for (const j of jobs) {
  const tag = `[${++n}/${jobs.length}] ${j.label}`;
  try {
    if (j.type === "logo") {
      if (!FORCE && fs.existsSync(j.out)) { console.log(`${tag} cached`); continue; }
      ffmpeg(["-y", "-i", j.src, "-vf", "scale=256:256:force_original_aspect_ratio=increase,crop=256:256", "-q:v", "3", j.out]);
      console.log(`${tag} ok`); continue;
    }
    if (!FORCE && fs.existsSync(j.mp4) && fs.existsSync(j.jpg)) { console.log(`${tag} cached`); continue; }
    ffmpeg(["-y", "-i", j.src,
      "-vf", "scale='min(540,iw)':-2:flags=lanczos,fps=30",
      "-c:v", "libx264", "-crf", "28", "-preset", "medium", "-profile:v", "main", "-pix_fmt", "yuv420p",
      "-c:a", "aac", "-b:a", "96k", "-ac", "2",
      "-movflags", "+faststart", "-map_metadata", "-1", j.mp4]);
    ffmpeg(["-y", "-ss", "1", "-i", j.mp4, "-frames:v", "1", "-q:v", "4", j.jpg]);
    console.log(`${tag} ok  ${Math.round(fs.statSync(j.mp4).size / 1024)} KB`);
  } catch (e) { console.error(`${tag} FAILED\n${e.message}`); }
}
console.log("done.");
