// AUTO-GENERATED by scripts/build-media.js — do not edit by hand.
// Re-run:  node scripts/build-media.js   (--force to re-encode everything)
const P = `${process.env.PUBLIC_URL || ""}/media/projects`;
const m = (f) => `${P}/${f}`;

const raw = {
  "granvisual": {
    "logo": "granvisual/logo.jpg",
    "cover": 0,
    "clips": [
      {
        "file": "granvisual/clip-01.mp4",
        "poster": "granvisual/clip-01.jpg",
        "title": "",
        "duration": 26
      },
      {
        "file": "granvisual/clip-02.mp4",
        "poster": "granvisual/clip-02.jpg",
        "title": "",
        "duration": 34
      }
    ]
  },
  "breaktheloop": {
    "logo": "breaktheloop/logo.jpg",
    "cover": 4,
    "clips": [
      {
        "file": "breaktheloop/clip-01.mp4",
        "poster": "breaktheloop/clip-01.jpg",
        "title": "Addiction is a loop that wants to convince you it’s unbreakable.",
        "duration": 35
      },
      {
        "file": "breaktheloop/clip-02.mp4",
        "poster": "breaktheloop/clip-02.jpg",
        "title": "",
        "duration": 32
      },
      {
        "file": "breaktheloop/clip-03.mp4",
        "poster": "breaktheloop/clip-03.jpg",
        "title": "",
        "duration": 24
      },
      {
        "file": "breaktheloop/clip-04.mp4",
        "poster": "breaktheloop/clip-04.jpg",
        "title": "The content was never the real problem.",
        "duration": 8
      },
      {
        "file": "breaktheloop/clip-05.mp4",
        "poster": "breaktheloop/clip-05.jpg",
        "title": "The real difference between before and after isn’t talent.",
        "duration": 13
      },
      {
        "file": "breaktheloop/clip-06.mp4",
        "poster": "breaktheloop/clip-06.jpg",
        "title": "This scene hits different when you’re in recovery.",
        "duration": 48
      },
      {
        "file": "breaktheloop/clip-07.mp4",
        "poster": "breaktheloop/clip-07.jpg",
        "title": "This was never about willpower.",
        "duration": 44
      },
      {
        "file": "breaktheloop/clip-08.mp4",
        "poster": "breaktheloop/clip-08.jpg",
        "title": "Your scars aren’t your weakness.",
        "duration": 7
      }
    ]
  },
  "ilgustodelgrano": {
    "logo": "ilgustodelgrano/logo.jpg",
    "cover": 3,
    "clips": [
      {
        "file": "ilgustodelgrano/clip-01.mp4",
        "poster": "ilgustodelgrano/clip-01.jpg",
        "title": "🍰Siamo entusiasti di presentarvi la deliziosa recensione dei nostri…",
        "duration": 54
      },
      {
        "file": "ilgustodelgrano/clip-02.mp4",
        "poster": "ilgustodelgrano/clip-02.jpg",
        "title": "",
        "duration": 37
      },
      {
        "file": "ilgustodelgrano/clip-03.mp4",
        "poster": "ilgustodelgrano/clip-03.jpg",
        "title": "Dolci Meraviglie!",
        "duration": 7
      },
      {
        "file": "ilgustodelgrano/clip-04.mp4",
        "poster": "ilgustodelgrano/clip-04.jpg",
        "title": "Ecco i Dolci che Stavate Aspettando!👇Preparatevi a un’esplosione di…",
        "duration": 17
      },
      {
        "file": "ilgustodelgrano/clip-05.mp4",
        "poster": "ilgustodelgrano/clip-05.jpg",
        "title": "ESPLORA IL GUSTO- Dolci Fatti in Casa che Ti Faranno Sognare!",
        "duration": 8
      },
      {
        "file": "ilgustodelgrano/clip-06.mp4",
        "poster": "ilgustodelgrano/clip-06.jpg",
        "title": "La SFIDA è iniziata!😠😡🤬I nostri cuori al cioccolato e albicocca s…",
        "duration": 15
      },
      {
        "file": "ilgustodelgrano/clip-07.mp4",
        "poster": "ilgustodelgrano/clip-07.jpg",
        "title": "Scopri il Paradiso dei Dolci!",
        "duration": 20
      }
    ]
  },
  "lotus": {
    "logo": "lotus/logo.jpg",
    "cover": 0,
    "clips": [
      {
        "file": "lotus/clip-01.mp4",
        "poster": "lotus/clip-01.jpg",
        "title": "Discover a world of endless possibilities!",
        "duration": 15
      },
      {
        "file": "lotus/clip-02.mp4",
        "poster": "lotus/clip-02.jpg",
        "title": "Elevate your everyday look with our clean and minimal geometric tee \ud83d…",
        "duration": 24
      }
    ]
  },
  "vexo": {
    "logo": "vexo/logo.jpg",
    "cover": 2,
    "clips": [
      {
        "file": "vexo/clip-01.mp4",
        "poster": "vexo/clip-01.jpg",
        "title": "€1,199 for 256GB vs €329 for 1TB 🤔The math doesnt lie.",
        "duration": 20
      },
      {
        "file": "vexo/clip-02.mp4",
        "poster": "vexo/clip-02.jpg",
        "title": "2026. Two types of creators.",
        "duration": 15
      },
      {
        "file": "vexo/clip-03.mp4",
        "poster": "vexo/clip-03.jpg",
        "title": "500MB per minute of 4K.",
        "duration": 17
      },
      {
        "file": "vexo/clip-04.mp4",
        "poster": "vexo/clip-04.jpg",
        "title": "512GB upgrade- €200 for 256GB moreVEXO- €329 for 1,000GB more40x the…",
        "duration": 27
      },
      {
        "file": "vexo/clip-05.mp4",
        "poster": "vexo/clip-05.jpg",
        "title": "Cable transfer- 45+ minutes.",
        "duration": 18
      },
      {
        "file": "vexo/clip-06.mp4",
        "poster": "vexo/clip-06.jpg",
        "title": "Golden hour waits for no one.",
        "duration": 10
      },
      {
        "file": "vexo/clip-07.mp4",
        "poster": "vexo/clip-07.jpg",
        "title": "Monthly fees.",
        "duration": 16
      },
      {
        "file": "vexo/clip-08.mp4",
        "poster": "vexo/clip-08.jpg",
        "title": "Phone connected.",
        "duration": 12
      },
      {
        "file": "vexo/clip-09.mp4",
        "poster": "vexo/clip-09.jpg",
        "title": "storage full hits different when youre getting paid 💀 link in bio",
        "duration": 10
      },
      {
        "file": "vexo/clip-10.mp4",
        "poster": "vexo/clip-10.jpg",
        "title": "Storage full isnt a notification.",
        "duration": 26
      },
      {
        "file": "vexo/clip-11.mp4",
        "poster": "vexo/clip-11.jpg",
        "title": "Storage full isnt a notification.",
        "duration": 27
      },
      {
        "file": "vexo/clip-12.mp4",
        "poster": "vexo/clip-12.jpg",
        "title": "That notification hits different when the shot is perfect 😤1TB.",
        "duration": 9
      },
      {
        "file": "vexo/clip-13.mp4",
        "poster": "vexo/clip-13.jpg",
        "title": "the secret they dont share in tutorials 🤫",
        "duration": 16
      }
    ]
  },
  "viralify": {
    "logo": "viralify/logo.jpg",
    "cover": 0,
    "clips": [
      {
        "file": "viralify/clip-01.mp4",
        "poster": "viralify/clip-01.jpg",
        "title": "70 euro_! Ma hai visto cosa ti porti a casa_!",
        "duration": 14
      },
      {
        "file": "viralify/clip-02.mp4",
        "poster": "viralify/clip-02.jpg",
        "title": "Ansie da Caduta_ Non più!",
        "duration": 28
      },
      {
        "file": "viralify/clip-03.mp4",
        "poster": "viralify/clip-03.jpg",
        "title": "Arent you exited 😂🙈",
        "duration": 20
      },
      {
        "file": "viralify/clip-04.mp4",
        "poster": "viralify/clip-04.jpg",
        "title": "Before you say it — yes, we know.",
        "duration": 24
      },
      {
        "file": "viralify/clip-05.mp4",
        "poster": "viralify/clip-05.jpg",
        "title": "Come mettere in tasca 10K giochi_",
        "duration": 13
      },
      {
        "file": "viralify/clip-06.mp4",
        "poster": "viralify/clip-06.jpg",
        "title": "Fedele a Nintendo_ Vediamo se la nostra console può farti cambiare i…",
        "duration": 16
      },
      {
        "file": "viralify/clip-07.mp4",
        "poster": "viralify/clip-07.jpg",
        "title": "Giubbotto per cani, pratico e robusto",
        "duration": 18
      },
      {
        "file": "viralify/clip-08.mp4",
        "poster": "viralify/clip-08.jpg",
        "title": "Hour 6. No AC.",
        "duration": 30
      },
      {
        "file": "viralify/clip-09.mp4",
        "poster": "viralify/clip-09.jpg",
        "title": "If you hate sweating outside…",
        "duration": 29
      },
      {
        "file": "viralify/clip-10.mp4",
        "poster": "viralify/clip-10.jpg",
        "title": "Il REGALO perfetto per ogni fan di Pokémon!",
        "duration": 24
      },
      {
        "file": "viralify/clip-11.mp4",
        "poster": "viralify/clip-11.jpg",
        "title": "Le Mamme lo Adorano!",
        "duration": 12
      },
      {
        "file": "viralify/clip-12.mp4",
        "poster": "viralify/clip-12.jpg",
        "title": "Mai più acrobazie involontarie!",
        "duration": 33
      },
      {
        "file": "viralify/clip-13.mp4",
        "poster": "viralify/clip-13.jpg",
        "title": "Primi Passi Senza Preoccupazioni!",
        "duration": 12
      },
      {
        "file": "viralify/clip-14.mp4",
        "poster": "viralify/clip-14.jpg",
        "title": "Proteggi i primi passi del tuo bimbo con questo zainetto!",
        "duration": 13
      },
      {
        "file": "viralify/clip-15.mp4",
        "poster": "viralify/clip-15.jpg",
        "title": "Sicurezza per il tuo bimbo, serenità per te!",
        "duration": 33
      },
      {
        "file": "viralify/clip-16.mp4",
        "poster": "viralify/clip-16.jpg",
        "title": "Street Fighter_ Ce l'abbiamo e ti aspetta!",
        "duration": 11
      },
      {
        "file": "viralify/clip-17.mp4",
        "poster": "viralify/clip-17.jpg",
        "title": "Sweaty ponytail, sticky clothes, melting mascara — been there one too…",
        "duration": 29
      },
      {
        "file": "viralify/clip-18.mp4",
        "poster": "viralify/clip-18.jpg",
        "title": "TikTok made me buy it …and I get it now",
        "duration": 11
      },
      {
        "file": "viralify/clip-19.mp4",
        "poster": "viralify/clip-19.jpg",
        "title": "Two types of people at summer events.",
        "duration": 23
      }
    ]
  },
  "youscaleit": {
    "logo": "youscaleit/logo.jpg",
    "cover": 0,
    "clips": [
      {
        "file": "youscaleit/clip-01.mp4",
        "poster": "youscaleit/clip-01.jpg",
        "title": "2 hours a week wasted on scheduling.",
        "duration": 30
      },
      {
        "file": "youscaleit/clip-02.mp4",
        "poster": "youscaleit/clip-02.jpg",
        "title": "Carousel scheduling across 5 platforms.",
        "duration": 18
      },
      {
        "file": "youscaleit/clip-03.mp4",
        "poster": "youscaleit/clip-03.jpg",
        "title": "Cross-postingOne post.",
        "duration": 18
      },
      {
        "file": "youscaleit/clip-04.mp4",
        "poster": "youscaleit/clip-04.jpg",
        "title": "Every post I schedule comes with an automatic reply — heres whyA link…",
        "duration": 21
      },
      {
        "file": "youscaleit/clip-05.mp4",
        "poster": "youscaleit/clip-05.jpg",
        "title": "Free tool inside YouScaleIt that turns plain text into platform-perfe…",
        "duration": 20
      },
      {
        "file": "youscaleit/clip-06.mp4",
        "poster": "youscaleit/clip-06.jpg",
        "title": "I batch 3 weeks of content in one sitting — this is the systemI sit d…",
        "duration": 26
      },
      {
        "file": "youscaleit/clip-07.mp4",
        "poster": "youscaleit/clip-07.jpg",
        "title": "I never publish without checking this firstBefore anything goes live…",
        "duration": 21
      },
      {
        "file": "youscaleit/clip-08.mp4",
        "poster": "youscaleit/clip-08.jpg",
        "title": "Link in bio",
        "duration": 44
      },
      {
        "file": "youscaleit/clip-09.mp4",
        "poster": "youscaleit/clip-09.jpg",
        "title": "One afternoon.",
        "duration": 20
      },
      {
        "file": "youscaleit/clip-10.mp4",
        "poster": "youscaleit/clip-10.jpg",
        "title": "One post. Five platforms.",
        "duration": 25
      },
      {
        "file": "youscaleit/clip-11.mp4",
        "poster": "youscaleit/clip-11.jpg",
        "title": "Posting more is not the answer.",
        "duration": 30
      },
      {
        "file": "youscaleit/clip-12.mp4",
        "poster": "youscaleit/clip-12.jpg",
        "title": "You dont need more content.",
        "duration": 25
      }
    ]
  }
};

export const media = Object.fromEntries(
  Object.entries(raw).map(([id, p]) => [id, {
    logo: p.logo ? m(p.logo) : null,
    cover: p.cover,
    clips: p.clips.map(c => ({ ...c, src: m(c.file), poster: m(c.poster) })),
  }])
);
